#!/usr/bin/env bash
# ==============================================================================
# Demo Workspace Setup Script (TSK-092)
#
# Generates a sample .orchestration/ directory with:
#   - active_intents.yaml  (Weather API demo intent)
#   - CLAUDE.md            (Shared brain template)
#   - intent_map.md        (Spatial index template)
#   - agent_trace.jsonl    (Empty trace log)
#   - .intentignore        (Default ignore patterns)
#   - README.md            (Docs)
#
# Usage: bash scripts/setup-demo-workspace.sh [target_dir]
#        Defaults to current directory if target_dir is not specified.
# ==============================================================================

set -euo pipefail

TARGET_DIR="${1:-.}"
ORCH_DIR="${TARGET_DIR}/.orchestration"

if [ -d "$ORCH_DIR" ]; then
  echo "⚠ .orchestration/ already exists at ${ORCH_DIR}. Aborting to avoid overwriting."
  exit 1
fi

echo "Creating .orchestration/ in ${TARGET_DIR}..."
mkdir -p "$ORCH_DIR"

# --- active_intents.yaml ---
cat > "$ORCH_DIR/active_intents.yaml" << 'YAML'
# Intent Catalog — Workspace-level declaration of all governed development tasks.
# Each intent constrains which files the AI agent may modify and why.

active_intents:
  - id: "INT-DEMO-001"
    name: "Weather API Integration"
    status: "PENDING"
    version: 1
    owned_scope:
      - "src/weather/**"
      - "src/api/weather.ts"
      - "tests/weather/**"
    constraints:
      - "Must not introduce new npm dependencies without approval"
      - "Must handle API rate limiting gracefully"
      - "Must include error handling for network failures"
    acceptance_criteria:
      - "Weather data can be fetched from OpenWeatherMap API"
      - "Temperature is displayed in both Celsius and Fahrenheit"
      - "API errors are caught and presented to the user"
      - "Unit tests cover all public functions"
    related_specs: []
    parent_intent: null
    tags:
      - "feature"
      - "api"
    created_at: "2026-02-20T10:00:00Z"
    updated_at: "2026-02-20T10:00:00Z"

  - id: "INT-DEMO-002"
    name: "Bug Fix: Null Pointer in User Profile"
    status: "PENDING"
    version: 1
    owned_scope:
      - "src/user/profile.ts"
      - "src/user/types.ts"
      - "tests/user/**"
    constraints:
      - "Minimal change — do not refactor unrelated code"
    acceptance_criteria:
      - "Profile page no longer crashes when user.avatar is null"
      - "Regression test added for null avatar scenario"
    related_specs: []
    parent_intent: null
    tags:
      - "bugfix"
    created_at: "2026-02-20T10:00:00Z"
    updated_at: "2026-02-20T10:00:00Z"
YAML

# --- CLAUDE.md ---
cat > "$ORCH_DIR/CLAUDE.md" << 'MD'
# Shared Brain - Demo Project

This file is the cross-session knowledge store. AI agents append lessons learned here
so that future sessions benefit from past mistakes and discoveries.

## Architecture Decisions

- Weather API uses OpenWeatherMap free tier
- User profile is server-side rendered

## Lessons Learned

(Entries are appended automatically by the governance system.)

## Active Sessions

<!-- machine-managed, do not edit -->
MD

# --- intent_map.md ---
cat > "$ORCH_DIR/intent_map.md" << 'MD'
# Intent → File Spatial Map

This file is auto-generated by the governance system. Do not edit manually.

## INT-DEMO-001: Weather API Integration

(No files modified yet)

## INT-DEMO-002: Bug Fix: Null Pointer in User Profile

(No files modified yet)
MD

# --- agent_trace.jsonl ---
touch "$ORCH_DIR/agent_trace.jsonl"

# --- .intentignore ---
cat > "$ORCH_DIR/.intentignore" << 'IGNORE'
# Files exempt from intent scope validation.
# These can be written by any intent without scope checks.

# Package manager lockfiles
package-lock.json
pnpm-lock.yaml
yarn.lock

# Build artifacts
dist/**
build/**
.next/**

# Editor config
.vscode/**
.idea/**

# Orchestration files themselves
.orchestration/**
IGNORE

# --- README.md ---
cat > "$ORCH_DIR/README.md" << 'MD'
# .orchestration/ — Intent-Driven Governance

This directory powers the intent-code traceability system.

## Files

| File | Purpose |
|------|---------|
| `active_intents.yaml` | Declares all active development intents with scope, constraints, and acceptance criteria |
| `CLAUDE.md` | Cross-session shared memory for lessons learned and architecture decisions |
| `intent_map.md` | Auto-generated spatial index mapping intents to modified files |
| `agent_trace.jsonl` | Append-only audit log of all AI agent mutations |
| `.intentignore` | Gitignore-style patterns for files exempt from scope enforcement |

## How It Works

1. Before modifying code, the AI agent must call `select_active_intent(intent_id="...")`.
2. The hook system validates that the target file is within the intent's `owned_scope`.
3. All mutations are logged to `agent_trace.jsonl` with pre/post SHA-256 hashes.
4. Lessons learned from failures are auto-appended to `CLAUDE.md`.

## Status Values

| Status | Meaning |
|--------|---------|
| `PENDING` | Declared but not yet started |
| `IN_PROGRESS` | Actively being worked on |
| `BLOCKED` | Waiting on external dependency |
| `COMPLETE` | All acceptance criteria met |
| `ARCHIVED` | No longer relevant |
MD

echo "✓ Demo workspace created at ${ORCH_DIR}/"
echo ""
echo "Files created:"
ls -la "$ORCH_DIR/"
echo ""
echo "Next steps:"
echo "  1. Open the project in your IDE"
echo "  2. The governance system will auto-detect .orchestration/"
echo "  3. The AI agent will be required to call select_active_intent before writing files"
